# config/database.yml

default: &default
  adapter: postgresql
  encoding: utf8
  host: localhost
  pool: 5
  username: awais
  password: admin123

development:
  <<: *default
  database: test_task_development

test:
  <<: *default
  database: test_task_test

production:
  <<: *default
  database: your_app_name_production
  host: <%= ENV['DATABASE_HOST'] %>
  port: <%= ENV['DATABASE_PORT'] %>
